
LIB_NAME=RedRectangle
CFLAGS=-DDEBUG -fblocks
LDLIBS=-llog -landroid -lCoreFoundation -lFoundation -lNAOpenGLES -lNAUIKit
OBJECTS = \
    rd_app_glue.o \
    rd_main.o \
    AppDelegate.o \
    RRSolidView.o \

include ${MYOS_PATH}/sdk/$(BASE_OS)/makefile-shared
