
LIB_NAME=BigApple
CFLAGS=-DDEBUG -fblocks
LDLIBS= -llog -landroid -lCoreFoundation -lFoundation -lNAOpenGLES -lNAUIKit -lNACoreGraphics

OBJECTS = \
    rd_app_glue.o \
    rd_main.o \
    AppDelegate.o \

include ${MYOS_PATH}/android/sdk/resources/makefile-shared
