
#APP_NAME=EnvironmentVariables

#OUTPUT=$(APP_NAME)
#CC=clang
#files=main.c

#all:$(files)
#	$(CC) main.c -o $(OUTPUT)

APP_NAME=EnvironmentVariables
OBJECTS = \
    main.o \

include ${MY_FRAMEWORKS_PATH}/resources/makefile-executable
