
LIB_NAME=Gradients
CFLAGS=-DDEBUG -fblocks
LDLIBS= -llog -landroid -lCoreFoundation -lFoundation -lNAOpenGLES -lNAUIKit -lNACoreGraphics -lNACoreAnimation
OBJECTS = \
    rd_app_glue.o \
    rd_main.o \
    AppDelegate.o \
    GradientsView.o \

include ${MYOS_PATH}/sdk/$(BASE_OS)/makefile-shared
