
APP_NAME=Shapes

LDLIBS=-lCoreFoundation -lFoundation -lCoreGraphics

OBJECTS = \
    main.o \
    arcs.o \
    ovals.o \
    rects.o \
    shapes.o \

include ${MYOS_PATH}/sdk/$(BASE_OS)/makefile-executable
